### ISSUE TITLE
HomieV3 with python 2.7 does not work

### ISSUE THREAD

**Issue by rfaelens** [mjcumming/HomieV3#9]
When simply running the test script:

```
pi@bureau:~/HomieV3 $ python test_temp_hum.py
Traceback (most recent call last):
  File "test_temp_hum.py", line 15, in <module>
    temp_hum = Device_Temperature_Humidity(name ='Temp Hum', mqtt_settings=mqtt_settings)
  File "/home/pi/HomieV3/homie/device_temperature.py", line 15, in __init__
    super().__init__ (device_id, name, homie_settings, mqtt_settings)
TypeError: super() takes at least 1 argument (0 given)
pi@bureau:~/HomieV3 $
```

This occurs however which way I try to use HomieV3.
It does work when using Python3. Perhaps you should add a warning message, or at least remove Homie3 from the Python2.7 PIP repository...

**Comment by mjcumming** [comment]
setup.py does specify Python 3. not sure how to get pipy to remove it from 2.7
